version: '2'
services:
    fuzmono-app:
        image: fuzmono
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fuzmono-mysql:3306/fuzmono?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fuzmono-mysql:
        extends:
            file: mysql.yml
            service: fuzmono-mysql
