apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fuzmicros
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fuzmicros
    spec:
      containers:
      - name: fuzmicros-app
        image: dolpfuz/fuzmicros
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_CLOUD_CONSUL_HOST
          value: consul.default.svc.cluster.local
        - name: SPRING_CLOUD_CONSUL_PORT
          value: "8500"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://fuzmicros-mysql.default.svc.cluster.local:3306/fuzmicros?useUnicode=true&characterEncoding=utf8&useSSL=false
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: web
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /management/health
            port: web
        livenessProbe:
          httpGet:
            path: /management/health
            port: web
          initialDelaySeconds: 180

